### ISSUE TITLE
alignment of 10 million COVID19 genomes

### ISSUE THREAD

**Issue by Shicheng-Guo** [PoonLab/MiCall#43]
Dear Art, 

I am wondering does GISAID provide an aligned COVID19 sequence or if only raw fastq is provided and others should make alignment by the user? How long times it will take if we want to alignment of 10 million COVID19 genomes?

Thanks.

Shicheng

**Comment by ArtPoon** [comment]
GISAID does provide a multiple sequence alignment that you can access if you have a registered user account.  You can reach it by selecting "EpiCoV", then "Downloads", and "MSAfull0608", for example.
Do not attempt to generate an alignment of 10 million genomes using conventional methods (i.e., running the sequences through ClustalW or MAFFT).  It will take forever.  The standard practice is to use pairwise alignment against a reference genome.  This is the method that we use for CoVizu, for example, and there is a more user-friendly implementation of this technique here:
https://github.com/niemasd/ViralMSA

**Comment by Shicheng-Guo** [comment]
Thank you so much Art!! You are really helpful!! Shicheng

**Comment by Shicheng-Guo** [comment]
I notice GISAID have 4 MSA files. I can understand the meanings for full vs codon? What's the difference between unmasked and masked? 

```
MSA full0608 (1164 MB)
MSA codon0611 (1177 MB)
MSA unmasked0613 (672 MB)
MSA masked0613 (646 MB)
```
Thanks. 

Shicheng
